version: "3.8"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.8.0.0/16'

services:
  web:
    build:
      context: ./
      # dockerfile: ./dockerfile_pc
    # container_name: westman/ichatgpt-frontend
    image: westman/ichatgpt-frontend
    restart: always
    ports:
      - '3000:3000'
    # command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
        network:
          ipv4_address: 177.8.0.12
  backend:
    build:
      context: ./
      # dockerfile: ./dockerfile_pc
    # container_name: westman/ichatgpt-backend
    image: westman/ichatgpt-backend
    restart: always
    ports:
      - '5001:5001'
    networks:
        network:
          ipv4_address: 177.8.0.13