version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "5001:5000"

  frontend:
    build:
      context: .
      dockerfile: client/dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5001

