version: "3.8"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.8.0.0/16'

services:
  frontend:
    image: ghcr.io/robin021/ichatgptweb:main
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
        network:
          ipv4_address: 177.8.0.10
    env_file:
      - ./.env
  backend:
    image: ghcr.io/robin021/ichatgpt:main
    ports:
      - "5001:5001"
    networks:
        network:
          ipv4_address: 177.8.0.2
    env_file:
      - ./.env
  watchtower:
    image: containrrr/watchtower
    command: --interval 300