name: iChatGPT-docker-images

on:
  push:
    branches:    
      - main
    tags:
      - v*

env:
  APP_NAME: ichatgpt
  DOCKERHUB_REPO: westman/ichatgpt-backend
  DOCKERHUB_REPO_FRONTEND: westman/ichatgpt-frontend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      -
        name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
     -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}-frontend
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO_FRONTEND }}:latest
            ${{ env.DOCKERHUB_REPO_FRONTEND }}:${{ env.APP_VERSION }}